export const countryCalendars = {
    Afghanistan: 'en.af',
    Albania: 'en.al',
    Algeria: 'en.dz',
    'American Samoa': 'en.as',
    Andorra: 'en.ad',
    Angola: 'en.ao',
    Anguilla: 'en.ai',
    'Antigua and Barbuda': 'en.ag',
    Argentina: 'en.ar',
    Armenia: 'en.am',
    Aruba: 'en.aw',
    Australia: 'en.australian',
    Austria: 'en.austrian',
    Azerbaijan: 'en.az',
    Bahamas: 'en.bs',
    Bahrain: 'en.bh',
    Bangladesh: 'en.bd',
    Barbados: 'en.bb',
    Belarus: 'en.by',
    Belgium: 'en.be',
    Belize: 'en.bz',
    Benin: 'en.bj',
    Bermuda: 'en.bm',
    Bhutan: 'en.bt',
    Bolivia: 'en.bo',
    'Bosnia and Herzegovina': 'en.ba',
    Botswana: 'en.bw',
    Brazil: 'en.brazilian',
    'British Virgin Islands': 'en.vg',
    'Brunei Darussalam': 'en.bn',
    Bulgaria: 'en.bulgarian',
    'Burkina Faso': 'en.bf',
    Burundi: 'en.bi',
    Cambodia: 'en.kh',
    Cameroon: 'en.cm',
    Canada: 'en.canadian',
    'Cape Verde': 'en.cv',
    'Cayman Islands': 'en.ky',
    'Central African Republic': 'en.cf',
    Chad: 'en.td',
    Chile: 'en.cl',
    China: 'en.china',
    Colombia: 'en.co',
    Comoros: 'en.km',
    Congo: 'en.cg',
    'Cook Islands': 'en.ck',
    'Costa Rica': 'en.cr',
    "Côte d'Ivoire": 'en.ci',
    Croatia: 'en.croatian',
    Cuba: 'en.cu',
    Curaçao: 'en.cw',
    Cyprus: 'en.cy',
    Czechia: 'en.czech',
    "Democratic People's Republic of Korea": 'en.kp',
    Denmark: 'en.danish',
    Djibouti: 'en.dj',
    Dominica: 'en.dm',
    'Dominican Republic': 'en.do',
    Ecuador: 'en.ec',
    Egypt: 'en.eg',
    'El Salvador': 'en.sv',
    'Equatorial Guinea': 'en.gq',
    Eritrea: 'en.er',
    Estonia: 'en.ee',
    Ethiopia: 'en.et',
    'Falkland Islands (Malvinas)': 'en.fk',
    'Faroe Islands': 'en.fo',
    'Federated States of Micronesia': 'en.fm',
    Fiji: 'en.fj',
    Finland: 'en.finnish',
    France: 'en.french',
    'French Guiana': 'en.gf',
    'French Polynesia': 'en.pf',
    Gabon: 'en.ga',
    Gambia: 'en.gm',
    Georgia: 'en.ge',
    Germany: 'en.german',
    Ghana: 'en.gh',
    Gibraltar: 'en.gi',
    Greece: 'en.greek',
    Greenland: 'en.gl',
    Grenada: 'en.gd',
    Guam: 'en.gu',
    Guatemala: 'en.gt',
    Guernsey: 'en.gg',
    Guinea: 'en.gn',
    'Guinea-Bissau': 'en.gw',
    Guyana: 'en.gy',
    Haiti: 'en.ht',
    'Holy See (Vatican City State)': 'en.va',
    Honduras: 'en.hn',
    'Hong Kong': 'en.hong_kong',
    Hungary: 'en.hungarian',
    Iceland: 'en.is',
    India: 'en.indian',
    Indonesia: 'en.indonesian',
    Iraq: 'en.iq',
    Ireland: 'en.irish',
    'Islamic Republic of Iran': 'en.ir',
    'Isle of Man': 'en.im',
    Israel: 'en.jewish',
    Italy: 'en.italian',
    Jamaica: 'en.jm',
    Japan: 'en.japanese',
    Jersey: 'en.je',
    Jordan: 'en.jo',
    Kazakhstan: 'en.kz',
    Kenya: 'en.ke',
    Kiribati: 'en.ki',
    Kuwait: 'en.kw',
    Kyrgyzstan: 'en.kg',
    "Lao People's Democratic Republic": 'en.la',
    Latvia: 'en.latvian',
    Lebanon: 'en.lb',
    Lesotho: 'en.ls',
    Liberia: 'en.lr',
    Libya: 'en.ly',
    Liechtenstein: 'en.li',
    Lithuania: 'en.lithuanian',
    Luxembourg: 'en.lu',
    Macao: 'en.mo',
    Madagascar: 'en.mg',
    Malawi: 'en.mw',
    Malaysia: 'en.malaysia',
    Maldives: 'en.mv',
    Mali: 'en.ml',
    Malta: 'en.mt',
    'Marshall Islands': 'en.mh',
    Martinique: 'en.mq',
    Mauritania: 'en.mr',
    Mauritius: 'en.mu',
    Mayotte: 'en.yt',
    Mexico: 'en.mexican',
    Moldova: 'en.md',
    Monaco: 'en.mc',
    Mongolia: 'en.mn',
    Montenegro: 'en.me',
    Montserrat: 'en.ms',
    Morocco: 'en.ma',
    Mozambique: 'en.mz',
    Myanmar: 'en.mm',
    Namibia: 'en.na',
    Nauru: 'en.nr',
    Nepal: 'en.np',
    Netherlands: 'en.dutch',
    'New Caledonia': 'en.nc',
    'New Zealand': 'en.new_zealand',
    Nicaragua: 'en.ni',
    Niger: 'en.ne',
    Nigeria: 'en.ng',
    'Northern Mariana Islands': 'en.mp',
    Norway: 'en.norwegian',
    Oman: 'en.om',
    Pakistan: 'en.pk',
    Palau: 'en.pw',
    Panama: 'en.pa',
    'Papua New Guinea': 'en.pg',
    Paraguay: 'en.py',
    Peru: 'en.pe',
    Philippines: 'en.philippines',
    Poland: 'en.polish',
    Portugal: 'en.portuguese',
    'Puerto Rico': 'en.pr',
    Qatar: 'en.qa',
    'Republic of Korea': 'en.south_korea',
    Réunion: 'en.re',
    Romania: 'en.romanian',
    'Russian Federation': 'en.russian',
    Rwanda: 'en.rw',
    'Saint Barthélemy': 'en.bl',
    'Saint Helena': 'en.sh',
    'Saint Kitts and Nevis': 'en.kn',
    'Saint Lucia': 'en.lc',
    'Saint Martin (French part)': 'en.mf',
    'Saint Pierre and Miquelon': 'en.pm',
    'Saint Vincent and the Grenadines': 'en.vc',
    Samoa: 'en.ws',
    'San Marino': 'en.sm',
    'Sao Tome and Principe': 'en.st',
    'Saudi Arabia': 'en.saudiarabian',
    Senegal: 'en.sn',
    Serbia: 'en.rs',
    Seychelles: 'en.sc',
    'Sierra Leone': 'en.sl',
    Singapore: 'en.singapore',
    'Sint Maarten (Dutch part)': 'en.sx',
    Slovakia: 'en.slovak',
    Slovenia: 'en.slovenian',
    'Solomon Islands': 'en.sb',
    Somalia: 'en.so',
    'South Africa': 'en.sa',
    'South Sudan': 'en.ss',
    Spain: 'en.spain',
    'Sri Lanka': 'en.lk',
    Sudan: 'en.sd',
    Suriname: 'en.sr',
    Swaziland: 'en.sz',
    Sweden: 'en.swedish',
    Switzerland: 'en.ch',
    'Syrian Arab Republic': 'en.sy',
    Taiwan: 'en.taiwan',
    Tajikistan: 'en.tj',
    Thailand: 'en.th',
    'The Democratic Republic of the Congo': 'en.cd',
    'The Former Yugoslav Republic of Macedonia': 'en.mk',
    'Timor-Leste': 'en.tl',
    Togo: 'en.tg',
    Tonga: 'en.to',
    'Trinidad and Tobago': 'en.tt',
    Tunisia: 'en.tn',
    Turkey: 'en.turkish',
    Turkmenistan: 'en.tm',
    'Turks and Caicos Islands': 'en.tc',
    Tuvalu: 'en.tv',
    'U.S. Virgin Islands': 'en.vi',
    Uganda: 'en.ug',
    Ukraine: 'en.ukrainian',
    'United Arab Emirates': 'en.ae',
    'United Kingdom': 'en.uk',
    'United Republic of Tanzania': 'en.tz',
    'United States': 'en.usa',
    Uruguay: 'en.uy',
    Uzbekistan: 'en.uz',
    Vanuatu: 'en.vu',
    Venezuela: 'en.ve',
    Vietnam: 'en.vietnamese',
    'Wallis and Futuna': 'en.wf',
    Yemen: 'en.ye',
    Zambia: 'en.zm',
    Zimbabwe: 'en.zw',
};
